* root
  多记录些,记录到你自己都无话可说了,那么就会遗忘了.
** 事件
   2016-08-18 17:34:37 Thu NZST
   在商店门口被勒索?
   5:00pm,人流量也很大的时候,
** 不友善
   其实要拒绝掉对方的理由应该是没有问题的.
   那么为什么你不拒绝掉呢?
   不友善?
   你从不善于拒绝,因为不想表现的不友善.
   当然这不是出于善意,而是一种行为模式吧.
   上一次非本意的无法拒绝是什么时候?这个倒是记得.
** 行为模式
   确切的说这个行为模式甚至不是国内养成的,
   这个行为模式是pathway中养成的,不管内在如何,所以人都表现出非常善意,
   随时乐于帮助的样子,虽然你不确定你如果真的寻求帮助的话,对方是否会立刻改变氛围.
   这样的氛围,这就让我们在用英语交流的第一时刻就感觉需要切换到这种行为模式.
   虽然不知是否有意,但是在进入这个氛围后,你会感觉不友善是一种罪过.
   所以无法拒绝的实质是,你不想承担罪过.
   至少从模式上来说,当时的英语氛围就是让我陷入了这样的行为模式.
*** 伪装
    这是一种类似伪装一样的性质的东西,明明本性并非如此,但是切换到英语环境后,就变得似乎不得不伪装然后融入其中.
    我想,对于原本就处于这种环境的当地人来说,应该更清楚的知道回避这种问题吧.
    但是对于你这样的外来者,就不会那么容易做到了.
** 具体分析
   其实拒绝掉很简单吧,但是为什么你要排斥呢?
   当然本身情绪低落也是原因,
   
   另一方面是对方的意图,
   是否真的需要帮助呢?
   人流量不小,所以我想他们也做不了过分的事情.
   是单纯的撒网乞讨吗?
   
   当然很明显是针对华人,并且我是步行,信用卡还在手上.
   而且书包乱开着,再算上你的身形,劳累度,很明显的让人觉得很弱势吧.
   就这个意义来说,他们看来是针对弱者下手的.
   总觉得很有即视感,不过想不到之前有类似的事情,总不至于是记忆故意遗忘了吧?
** 实用角度与防范
   从实用角度来说,这不是首当其冲的经济问题,反而情感和注意力上的影响更大.
   排查这些因素,把自己伪装成普通人,避免下次这样的问题很必要吧.
   另外就是再次路过那里,去那边的商店会成问题吗?是不是最近不能去那里了呢?
   被人抓住过一次机会的话,第二次的几率就会很大了吧.
** 抱怨
   这件事情不适合和任何人抱怨.
   但是如果你无法接受这样的suffer无缘由的消散掉的话,那么我们只能在这里记录了.
** 我的责任
   对抗恶意,纠正社会风气,这是我的责任吗?
   这或许是一般人的责任,但是人各有长,这不是我擅长的事情.
   所以你不浪费精力在这种极度不擅长的事情上,我觉得并不是该被指责的.
   
   你需要做的是,尽量避免这种事情再发生,以及尽快调整情绪.

2016-08-18 18:13:38 Thu NZST
差不多到此为止了,
经济损失+购物禁区+情绪调整
然后我们该回到自己该做的事情上了.
** 情绪
   比起尊严外,其实更多的情绪问题可能是生存威胁感.因为感受到了可能的敌意
*** 梦 
    2016-08-19 13:26:04 Fri NZST
    在拥挤的小路开车,撞到东西,
    下车步行.
    看到有些人在前面一个坑中干活.
    其中一个人无缘由的向我扔砖
    用手盖住头,感觉确实被砸了
    然后他又扔了.

    问题应该是不适应,对于突然而来的接触,
    完全没有头绪对方是善意还是恶意的.
    很混乱,不知道该用什么样的感情应对.
    当袭击方是如此理所当然的攻击的时候,你反而会困惑自己用敌意应对是否恰当
**** 功用
     虽然现在我很难意识到,
     但是根据经验来说,做梦大概的确会起到一定的佛洛依德所说的补偿效果.
     梦的内容虽然令人不快,但是似乎的确能帮助削弱这部分记忆.
     或者说是削减了针对这部分记忆的注意力
**** 进一步假说
     那么为什么要做同类型的梦呢?
     麻木适应吗?

     是通过回忆然后触发情绪.
     要消除它的话,可能有多种方式
      - 通过时间,麻木认可
	比较实际的情形是,事件本身对当前并没有太多影响了,所以就不在乎了.
      - 构建一个逻辑思维习惯,在回忆的同时否定情绪
	这种老实说似乎并不是很现实
	一般来说主动的自我说服/催眠应该属于这种.
     首先,如上所说,这和近期记忆有关,时间长了就会模糊掉事件本身.
     当细节变模糊的时候,其触发对应情绪的能力应该会变弱.
     因此,重点就是模糊掉记忆本身,或者说通过其他强烈的事件,排除掉这个事件上的注意力.
     所以重点是网络如何消除这份记忆的真实感的.
     
     麻木适应和模糊记忆似乎是两个不同的方向.
     麻木是为了消除同等级别细节的记忆触发情绪的能力.
     而模糊记忆细节本身肯定会减弱触发情绪的能力.
     那么梦属于哪种呢?促进麻木适应?还是说制造同类记忆,产生模糊混淆事件细节的效果?
     另外麻木适应应该是有多种形式,
     - 首先应该是属于人本能性的麻木能力,应该说属于被动性质
     - 另外一种,一般来说应该会被称为"成熟",
       应该说是人在经历了很多之后,主动做到的忽视不必要的信息的能力
     
     时间本身肯定可以模糊记忆.
     而麻木机制,如果真的存在的话,应该和你重复同类型思考的次数有关联.
     
     - 一般常识的说法
       是,人在清醒的时候,思维是受约束的,
       梦可以消除这种约束,让你真正接触到你潜意识不想接触的情绪.
       匹配上麻木机制/适应机制的话,人在接触了不想接触的情绪之后,才会开始适应.

     所以下一步,我们可以尝试合理化这个麻木/适应机制吗?

     我想不清楚,到底是否情绪减弱了,以及它如何减弱了.
     稍微比较清晰的一点是,内在的冲动性或许减少了.
     如果说到削减冲动性的话,应该和满足有关.
     
     梦是否在什么意义上满足了你内在的冲动?
     是辨析能力吗?
     因为社会性的恶意一般都是带着伪装的,即使说理性上你明确知道这是恶意,
     但是感性上,由于教化约束,对方大概有能力让你误认为是自己犯错了,而无法产生明确的敌意.
     如果这种能力是真实存在的话,对于袭击者来说是很有利的,有经验的袭击者一定对此很熟练.
     
     因此,这就在你心里留下了一个问题,
     由于教化的约束,你甚至不知道自己是否有权利以恶意回应对方.
     也就是说,你内在的冲动是恶意,但是被教化约束了.

     这个梦帮你把条理理清了,虽然同样在梦中,我在被袭击之后,感觉是迷茫多于以恶意回应.
     实际上原本我们的状态应该就是迷茫,不知如何应对.
     这个梦去除了不必要的细节,因此让你感受的更清晰了.
**** 梦的实现
     说到这里有个很有趣的问题,按这种描述,这样的梦是如何实现的呢?
     这个描述太复杂了.

     我想重点在于,这个梦,是为了重现你曾体验的情绪的节奏而存在的.
     因此,那些事件中不会影响情绪的因素应该就不会被复现.
     
     从算法的角度上来说,
     原始数据是我在事件中的情绪波动走向,
     在梦境中,在确保可以被认可的前提下,梦推进剧情走向.
     然后,在一个场景中,未来的走向应该会有多个选择,
     这个时候,梦会探测,并选择那个和会带来原始事件中的情绪波动一样的情绪的选择.
     
     这个机制的一个可能的证据是这样一种体验:
     在噩梦中,如果自己担忧某件事情会发生,这件事情就会发生.
     而这种担忧,应该是因为现实中经历的原始事件,留下的情绪波动痕迹给出的预测.
**** 功效
     回过头来,依据这个实现来讨论梦的功效.
     - 首先是原始事件给你留下一份情绪波动
     - 在梦中,当你面对一个相近的场景的时候,这个情绪波动会带给你一个预测,一个忧虑.
     - 梦会直接实现这个忧虑.
     - 到此为止的转换过程是, 原始事件 -> 情绪波动 -> 忧虑预测 -> 一个噩梦
     很显然,通过这个转换,很多细节会被丢掉.
     产生的效果是,直接思考原始事件会让你迷茫,但是最后产生的噩梦则会去掉枝叶,留下脉络,变得很清晰.
     就好像一份index一样.
     通过这份index回溯原始事件,一般来说我不会想要主动去回溯.
     应该说是无意识回溯原始事件的时候,由于index的存在,你的思维会变清晰,而不再迷茫.
     因此,你可以很快的做出决断,而不再困扰堵塞在部分被梦理清的问题上.
**** 再次总结.
     梦通过模拟原始事件,抽取出脉络的情绪.
     由于人的短时记忆很有限,这个脉络情绪必然是很精短的.
     实际上,人在清醒的时候,如果纠结细节的话,应该会很难理清自己对特定事件的整体感受.
     也可能受恐惧等因素阻碍而不愿回忆.
     恐惧应该不是梦帮助解决的,这不是需要精简理清事件脉络的问题.
     但是对于让你迷茫的问题来说,梦可以整理出整体的感受,让你不再困扰吧
     
     
     
     
