* root
  多记录些,记录到你自己都无话可说了,那么就会遗忘了.
** 事件
   2016-08-18 17:34:37 Thu NZST
   在商店门口被勒索?
   5:00pm,人流量也很大的时候,
** 不友善
   其实要拒绝掉对方的理由应该是没有问题的.
   那么为什么你不拒绝掉呢?
   不友善?
   你从不善于拒绝,因为不想表现的不友善.
   当然这不是出于善意,而是一种行为模式吧.
   上一次非本意的无法拒绝是什么时候?这个倒是记得.
** 行为模式
   确切的说这个行为模式甚至不是国内养成的,
   这个行为模式是pathway中养成的,不管内在如何,所以人都表现出非常善意,
   随时乐于帮助的样子,虽然你不确定你如果真的寻求帮助的话,对方是否会立刻改变氛围.
   这样的氛围,这就让我们在用英语交流的第一时刻就感觉需要切换到这种行为模式.
   虽然不知是否有意,但是在进入这个氛围后,你会感觉不友善是一种罪过.
   所以无法拒绝的实质是,你不想承担罪过.
   至少从模式上来说,当时的英语氛围就是让我陷入了这样的行为模式.
*** 伪装
    这是一种类似伪装一样的性质的东西,明明本性并非如此,但是切换到英语环境后,就变得似乎不得不伪装然后融入其中.
    我想,对于原本就处于这种环境的当地人来说,应该更清楚的知道回避这种问题吧.
    但是对于你这样的外来者,就不会那么容易做到了.
** 具体分析
   其实拒绝掉很简单吧,但是为什么你要排斥呢?
   当然本身情绪低落也是原因,
   
   另一方面是对方的意图,
   是否真的需要帮助呢?
   人流量不小,所以我想他们也做不了过分的事情.
   是单纯的撒网乞讨吗?
   
   当然很明显是针对华人,并且我是步行,信用卡还在手上.
   而且书包乱开着,再算上你的身形,劳累度,很明显的让人觉得很弱势吧.
   就这个意义来说,他们看来是针对弱者下手的.
   总觉得很有即视感,不过想不到之前有类似的事情,总不至于是记忆故意遗忘了吧?
** 实用角度与防范
   从实用角度来说,这不是首当其冲的经济问题,反而情感和注意力上的影响更大.
   排查这些因素,把自己伪装成普通人,避免下次这样的问题很必要吧.
   另外就是再次路过那里,去那边的商店会成问题吗?是不是最近不能去那里了呢?
   被人抓住过一次机会的话,第二次的几率就会很大了吧.
** 抱怨
   这件事情不适合和任何人抱怨.
   但是如果你无法接受这样的suffer无缘由的消散掉的话,那么我们只能在这里记录了.
** 我的责任
   对抗恶意,纠正社会风气,这是我的责任吗?
   这或许是一般人的责任,但是人各有长,这不是我擅长的事情.
   所以你不浪费精力在这种极度不擅长的事情上,我觉得并不是该被指责的.
   
   你需要做的是,尽量避免这种事情再发生,以及尽快调整情绪.

2016-08-18 18:13:38 Thu NZST
差不多到此为止了,
经济损失+购物禁区+情绪调整
然后我们该回到自己该做的事情上了.
** 情绪
   比起尊严外,其实更多的情绪问题可能是生存威胁感.因为感受到了可能的敌意
