(custom-set-faces
 '(calendar-weekend-header ((t (:foreground "Red"  ))))
 '(comint-highlight-input ((t (:foreground "White"  :weight bold ))))
 '(comint-highlight-prompt ((t (:foreground "BrightBlue"  ))))
 '(completions-annotations ((t (:foreground "White"  ))))
 '(completions-common-part ((t (:foreground "White"  ))))
 '(completions-first-difference ((t (:foreground "White"  :weight bold ))))
 '(cursor ((t (:foreground "White"  :weight bold ))))
 '(diary ((t (:foreground "Red"  ))))
 '(dired-directory ((t (:foreground "Blue"  :weight bold ))))
 '(dired-flagged ((t (:foreground "BrightRed"  :weight bold ))))
 '(dired-header ((t (:foreground "Green"  ))))
 '(dired-ignored ((t (:foreground "Green"  ))))
 '(dired-mark ((t (:foreground "Magenta"  ))))
 '(dired-marked ((t (:foreground "BrightYellow"  :weight bold ))))
 '(dired-perm-write ((t (:foreground "Red"  ))))
 '(dired-symlink ((t (:foreground "Cyan"  :weight bold ))))
 '(dired-warning ((t (:foreground "BrightRed"  :weight bold ))))
 '(eldoc-highlight-function-argument ((t (:foreground "White"  :weight bold ))))
 '(error ((t (:foreground "BrightRed"  :weight bold ))))
 '(escape-glyph ((t (:foreground "Red"  ))))
 '(evil-ex-commands ((t (:foreground "White"  ))))
 '(evil-ex-info ((t (:foreground "Red"  ))))
 '(evil-ex-lazy-highlight ((t (:foreground "White"  :weight bold ))))
 '(evil-ex-search ((t (:foreground "BrightCyan"  :weight bold ))))
 '(evil-ex-substitute-matches ((t (:foreground "White"  :weight bold ))))
 '(evil-ex-substitute-replacement ((t (:foreground "Red"  ))))
 '(file-name-shadow ((t (:foreground "Green"  ))))
 '(fixed-pitch ((t (:foreground "White"  ))))
 '(font-lock-builtin-face ((t (:foreground "Blue"  :weight bold ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "Red"  ))))
 '(font-lock-comment-face ((t (:foreground "Red"  ))))
 '(font-lock-constant-face ((t (:foreground "Magenta"  ))))
 '(font-lock-doc-face ((t (:foreground "Green"  ))))
 '(font-lock-function-name-face ((t (:foreground "Blue"  :weight bold ))))
 '(font-lock-keyword-face ((t (:foreground "Cyan"  :weight bold ))))
 '(font-lock-negation-char-face ((t (:foreground "White"  ))))
 '(font-lock-preprocessor-face ((t (:foreground "Blue"  :weight bold ))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "White"  :weight bold ))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "White"  :weight bold ))))
 '(font-lock-string-face ((t (:foreground "Green"  ))))
 '(font-lock-type-face ((t (:foreground "Green"  ))))
 '(font-lock-variable-name-face ((t (:foreground "Yellow"  ))))
 '(font-lock-warning-face ((t (:foreground "BrightRed"  :weight bold ))))
 '(fringe ((t (:foreground "White"  :weight bold ))))
 '(glyphless-char ((t (:foreground "White"  ))))
 '(header-line ((t (:foreground "White"  ))))
 '(help-argument-name ((t (:foreground "White"  ))))
 '(highlight ((t (:foreground "Black"  :weight bold ))))
 '(holiday ((t (:foreground "White"  :weight bold ))))
 '(info-header-node ((t (:foreground "BrightRed"  :weight bold ))))
 '(info-header-xref ((t (:foreground "BrightBlue"  ))))
 '(info-index-match ((t (:foreground "Black"  :weight bold ))))
 '(info-menu-header ((t (:foreground "White"  :weight bold ))))
 '(info-menu-star ((t (:foreground "Red"  ))))
 '(info-node ((t (:foreground "BrightRed"  :weight bold ))))
 '(info-title-1 ((t (:foreground "BrightGreen"  :weight bold ))))
 '(info-title-2 ((t (:foreground "Cyan"  :weight bold ))))
 '(info-title-3 ((t (:foreground "White"  :weight bold ))))
 '(info-title-4 ((t (:foreground "White"  :weight bold ))))
 '(info-xref ((t (:foreground "BrightBlue"  ))))
 '(info-xref-visited ((t (:foreground "Magenta"  ))))
 '(isearch ((t (:foreground "BrightCyan"  :weight bold ))))
 '(isearch-fail ((t (:foreground "White"  :weight bold ))))
 '(italic ((t (:foreground "White"  ))))
 '(lazy-highlight ((t (:foreground "White"  :weight bold ))))
 '(link ((t (:foreground "BrightBlue"  ))))
 '(link-visited ((t (:foreground "Magenta"  ))))
 '(match ((t (:foreground "Black"  :weight bold ))))
 '(menu ((t (:foreground "Black"  :weight bold ))))
 '(minibuffer-prompt ((t (:foreground "BrightBlue"  ))))
 '(mode-line ((t (:foreground "Black"  :weight bold ))))
 '(mode-line-buffer-id ((t (:foreground "White"  :weight bold ))))
 '(mode-line-emphasis ((t (:foreground "White"  :weight bold ))))
 '(mode-line-highlight ((t (:foreground "Black"  :weight bold ))))
 '(mode-line-inactive ((t (:foreground "Black"  :weight bold ))))
 '(mouse ((t (:foreground "White"  ))))
 '(next-error ((t (:foreground "BrightWhite"  :weight bold ))))
 '(nobreak-space ((t (:foreground "White"  :weight bold ))))
 '(org-agenda-calendar-event ((t (:foreground "White"  ))))
 '(org-agenda-calendar-sexp ((t (:foreground "White"  ))))
 '(org-agenda-clocking ((t (:foreground "Black"  :weight bold ))))
 '(org-agenda-column-dateline ((t (:foreground "Black"  :weight bold ))))
 '(org-agenda-current-time ((t (:foreground "Yellow"  ))))
 '(org-agenda-date ((t (:foreground "Blue"  :weight bold ))))
 '(org-agenda-date-today ((t (:foreground "Blue"  :weight bold ))))
 '(org-agenda-date-weekend ((t (:foreground "Blue"  :weight bold ))))
 '(org-agenda-diary ((t (:foreground "White"  ))))
 '(org-agenda-dimmed-todo-face ((t (:foreground "Yellow"  ))))
 '(org-agenda-done ((t (:foreground "Green"  ))))
 '(org-agenda-filter-category ((t (:foreground "Black"  :weight bold ))))
 '(org-agenda-filter-regexp ((t (:foreground "Black"  :weight bold ))))
 '(org-agenda-filter-tags ((t (:foreground "Black"  :weight bold ))))
 '(org-agenda-restriction-lock ((t (:foreground "Black"  :weight bold ))))
 '(org-agenda-structure ((t (:foreground "Blue"  :weight bold ))))
 '(org-archived ((t (:foreground "Green"  ))))
 '(org-block ((t (:foreground "Green"  ))))
 '(org-block-begin-line ((t (:foreground "Red"  ))))
 '(org-block-end-line ((t (:foreground "Red"  ))))
 '(org-checkbox ((t (:foreground "White"  :weight bold ))))
 '(org-checkbox-statistics-done ((t (:foreground "Green"  ))))
 '(org-checkbox-statistics-todo ((t (:foreground "BrightRed"  :weight bold ))))
 '(org-clock-overlay ((t (:foreground "Black"  :weight bold ))))
 '(org-code ((t (:foreground "Green"  ))))
 '(org-column ((t (:foreground "Black"  :weight bold ))))
 '(org-column-title ((t (:foreground "BrightBlack"  :weight bold ))))
 '(org-date ((t (:foreground "Magenta"  ))))
 '(org-date-selected ((t (:foreground "Black"  :weight bold ))))
 '(org-default ((t (:foreground "White"  ))))
 '(org-document-info ((t (:foreground "BrightBlue"  ))))
 '(org-document-info-keyword ((t (:foreground "Green"  ))))
 '(org-document-title ((t (:foreground "Blue"  :weight bold ))))
 '(org-done ((t (:foreground "Green"  ))))
 '(org-drawer ((t (:foreground "Blue"  :weight bold ))))
 '(org-ellipsis ((t (:foreground "Yellow"  ))))
 '(org-footnote ((t (:foreground "Magenta"  ))))
 '(org-formula ((t (:foreground "Red"  ))))
 '(org-headline-done ((t (:foreground "White"  ))))
 '(org-hide ((t (:foreground "BrightWhite"  ))))
 '(org-latex-and-related ((t (:foreground "Red"  ))))
 '(org-level-1 ((t (:foreground "Blue"  :weight bold ))))
 '(org-level-2 ((t (:foreground "Yellow"  ))))
 '(org-level-3 ((t (:foreground "Cyan"  :weight bold ))))
 '(org-level-4 ((t (:foreground "Red"  ))))
 '(org-level-5 ((t (:foreground "Green"  ))))
 '(org-level-6 ((t (:foreground "Magenta"  ))))
 '(org-level-7 ((t (:foreground "Blue"  :weight bold ))))
 '(org-level-8 ((t (:foreground "Green"  ))))
 '(org-link ((t (:foreground "BrightBlue"  ))))
 '(org-list-dt ((t (:foreground "White"  :weight bold ))))
 '(org-macro ((t (:foreground "Red"  ))))
 '(org-meta-line ((t (:foreground "Red"  ))))
 '(org-mode-line-clock ((t (:foreground "Black"  :weight bold ))))
 '(org-mode-line-clock-overrun ((t (:foreground "Red"  :weight bold ))))
 '(org-priority ((t (:foreground "Cyan"  :weight bold ))))
 '(org-property-value ((t (:foreground "White"  ))))
 '(org-quote ((t (:foreground "Green"  ))))
 '(org-scheduled ((t (:foreground "Green"  ))))
 '(org-scheduled-previously ((t (:foreground "Red"  ))))
 '(org-scheduled-today ((t (:foreground "Green"  ))))
 '(org-sexp-date ((t (:foreground "Magenta"  ))))
 '(org-special-keyword ((t (:foreground "Cyan"  :weight bold ))))
 '(org-table ((t (:foreground "BrightBlue"  ))))
 '(org-tag ((t (:foreground "White"  :weight bold ))))
 '(org-tag-group ((t (:foreground "White"  :weight bold ))))
 '(org-target ((t (:foreground "White"  ))))
 '(org-time-grid ((t (:foreground "Yellow"  ))))
 '(org-todo ((t (:foreground "BrightRed"  :weight bold ))))
 '(org-upcoming-deadline ((t (:foreground "Red"  ))))
 '(org-verbatim ((t (:foreground "Green"  ))))
 '(org-verse ((t (:foreground "Green"  ))))
 '(org-warning ((t (:foreground "BrightRed"  :weight bold ))))
 '(outline-1 ((t (:foreground "Blue"  :weight bold ))))
 '(outline-2 ((t (:foreground "Yellow"  ))))
 '(outline-3 ((t (:foreground "Cyan"  :weight bold ))))
 '(outline-4 ((t (:foreground "Red"  ))))
 '(outline-5 ((t (:foreground "Green"  ))))
 '(outline-6 ((t (:foreground "Magenta"  ))))
 '(outline-7 ((t (:foreground "Blue"  :weight bold ))))
 '(outline-8 ((t (:foreground "Green"  ))))
 '(query-replace ((t (:foreground "BrightCyan"  :weight bold ))))
 '(region ((t (:foreground "BrightWhite"  :weight bold ))))
 '(scroll-bar ((t (:foreground "White"  ))))
 '(secondary-selection ((t (:foreground "Black"  :weight bold ))))
 '(shadow ((t (:foreground "Green"  ))))
 '(show-paren-match ((t (:foreground "White"  :weight bold ))))
 '(show-paren-mismatch ((t (:foreground "BrightWhite"  :weight bold ))))
 '(success ((t (:foreground "BrightGreen"  :weight bold ))))
 '(tool-bar ((t (:foreground "Black"  ))))
 '(tooltip ((t (:foreground "Black"  :weight bold ))))
 '(trailing-whitespace ((t (:foreground "White"  :weight bold ))))
 '(tty-menu-disabled-face ((t (:foreground "BrightWhite"  :weight bold ))))
 '(tty-menu-enabled-face ((t (:foreground "BrightYellow"  :weight bold ))))
 '(tty-menu-selected-face ((t (:foreground "White"  :weight bold ))))
 '(underline ((t (:foreground "White"  ))))
 '(undo-tree-visualizer-active-branch-face ((t (:foreground "BrightBlack"  :weight bold ))))
 '(undo-tree-visualizer-current-face ((t (:foreground "Red"  ))))
 '(undo-tree-visualizer-default-face ((t (:foreground "BrightWhite"  ))))
 '(undo-tree-visualizer-register-face ((t (:foreground "Yellow"  ))))
 '(undo-tree-visualizer-unmodified-face ((t (:foreground "BrightCyan"  ))))
 '(variable-pitch ((t (:foreground "White"  ))))
 '(vertical-border ((t (:foreground "Black"  :weight bold ))))
 '(warning ((t (:foreground "BrightYellow"  :weight bold ))))
 '(window-divider ((t (:foreground "BrightWhite"  ))))
 '(window-divider-first-pixel ((t (:foreground "BrightWhite"  ))))
 '(window-divider-last-pixel ((t (:foreground "Black"  ))))
 '(bold ((t (:foreground "White"  ))))
 '(bold-italic ((t (:foreground "White"  ))))
 '(border ((t (:foreground "White"  :weight bold ))))
 '(buffer-menu-buffer ((t (:foreground "White"  ))))
 '(button ((t (:foreground "BrightBlue"  :weight bold ))))
 '(completions-annotations ((t (:foreground "White"  :weight bold ))))
 '(completions-common-part ((t (:foreground "White"  :weight bold ))))
 '(completions-first-difference ((t (:foreground "White"  ))))
 '(cursor ((t (:foreground "White"  ))))
 '(error ((t (:foreground "BrightRed"  ))))
 '(escape-glyph ((t (:foreground "Red"  :weight bold ))))
 '(evil-ex-commands ((t (:foreground "White"  :weight bold ))))
 '(evil-ex-info ((t (:foreground "Red"  :weight bold ))))
 '(evil-ex-lazy-highlight ((t (:foreground "White"  ))))
 '(evil-ex-search ((t (:foreground "BrightCyan"  ))))
 '(evil-ex-substitute-matches ((t (:foreground "White"  ))))
 '(evil-ex-substitute-replacement ((t (:foreground "Red"  :weight bold ))))
 '(file-name-shadow ((t (:foreground "Green"  :weight bold ))))
 '(fixed-pitch ((t (:foreground "White"  :weight bold ))))
 '(font-lock-builtin-face ((t (:foreground "Blue"  ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "Red"  :weight bold ))))
 '(font-lock-comment-face ((t (:foreground "Red"  :weight bold ))))
 '(font-lock-constant-face ((t (:foreground "Magenta"  :weight bold ))))
 '(font-lock-doc-face ((t (:foreground "Green"  :weight bold ))))
 '(font-lock-function-name-face ((t (:foreground "Blue"  ))))
 '(font-lock-keyword-face ((t (:foreground "Cyan"  ))))
 '(font-lock-negation-char-face ((t (:foreground "White"  :weight bold ))))
 '(font-lock-preprocessor-face ((t (:foreground "Blue"  ))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "White"  ))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "White"  ))))
 '(font-lock-string-face ((t (:foreground "Green"  :weight bold ))))
 '(font-lock-type-face ((t (:foreground "Green"  :weight bold ))))
 '(font-lock-variable-name-face ((t (:foreground "Yellow"  :weight bold ))))
 '(font-lock-warning-face ((t (:foreground "BrightRed"  ))))
 '(fringe ((t (:foreground "White"  ))))
 '(glyphless-char ((t (:foreground "White"  :weight bold ))))
 '(header-line ((t (:foreground "White"  :weight bold ))))
 '(help-argument-name ((t (:foreground "White"  :weight bold ))))
 '(highlight ((t (:foreground "Black"  ))))
 '(info-header-node ((t (:foreground "BrightRed"  ))))
 '(info-header-xref ((t (:foreground "BrightBlue"  :weight bold ))))
 '(info-index-match ((t (:foreground "Black"  ))))
 '(info-menu-header ((t (:foreground "White"  ))))
 '(info-menu-star ((t (:foreground "Red"  :weight bold ))))
 '(info-node ((t (:foreground "BrightRed"  ))))
 '(info-title-1 ((t (:foreground "BrightGreen"  ))))
 '(info-title-2 ((t (:foreground "Cyan"  ))))
 '(info-title-3 ((t (:foreground "White"  ))))
 '(info-title-4 ((t (:foreground "White"  ))))
 '(info-xref ((t (:foreground "BrightBlue"  :weight bold ))))
 '(info-xref-visited ((t (:foreground "Magenta"  :weight bold ))))
 '(isearch ((t (:foreground "BrightCyan"  ))))
 '(isearch-fail ((t (:foreground "White"  ))))
 '(italic ((t (:foreground "White"  :weight bold ))))
 '(lazy-highlight ((t (:foreground "White"  ))))
 '(link ((t (:foreground "BrightBlue"  :weight bold ))))
 '(link-visited ((t (:foreground "Magenta"  :weight bold ))))
 '(match ((t (:foreground "Black"  ))))
 '(menu ((t (:foreground "Black"  ))))
 '(minibuffer-prompt ((t (:foreground "BrightBlue"  :weight bold ))))
 '(mode-line ((t (:foreground "Black"  ))))
 '(mode-line-buffer-id ((t (:foreground "White"  ))))
 '(mode-line-emphasis ((t (:foreground "White"  ))))
 '(mode-line-highlight ((t (:foreground "Black"  ))))
 '(mode-line-inactive ((t (:foreground "Black"  ))))
 '(mouse ((t (:foreground "White"  :weight bold ))))
 '(next-error ((t (:foreground "BrightWhite"  ))))
 '(nobreak-space ((t (:foreground "White"  ))))
 '(query-replace ((t (:foreground "BrightCyan"  ))))
 '(region ((t (:foreground "BrightWhite"  ))))
 '(scroll-bar ((t (:foreground "White"  :weight bold ))))
 '(secondary-selection ((t (:foreground "Black"  ))))
 '(shadow ((t (:foreground "Green"  :weight bold ))))
 '(show-paren-match ((t (:foreground "White"  ))))
 '(show-paren-mismatch ((t (:foreground "BrightWhite"  ))))
 '(success ((t (:foreground "BrightGreen"  ))))
 '(tool-bar ((t (:foreground "Black"  :weight bold ))))
 '(tooltip ((t (:foreground "Black"  ))))
 '(trailing-whitespace ((t (:foreground "White"  ))))
 '(tty-menu-disabled-face ((t (:foreground "BrightWhite"  ))))
 '(tty-menu-enabled-face ((t (:foreground "BrightYellow"  ))))
 '(tty-menu-selected-face ((t (:foreground "White"  ))))
 '(underline ((t (:foreground "White"  :weight bold ))))
 '(undo-tree-visualizer-active-branch-face ((t (:foreground "BrightBlack"  ))))
 '(undo-tree-visualizer-current-face ((t (:foreground "Red"  :weight bold ))))
 '(undo-tree-visualizer-default-face ((t (:foreground "BrightWhite"  :weight bold ))))
 '(undo-tree-visualizer-register-face ((t (:foreground "Yellow"  :weight bold ))))
 '(undo-tree-visualizer-unmodified-face ((t (:foreground "BrightCyan"  :weight bold ))))
 '(variable-pitch ((t (:foreground "White"  :weight bold ))))
 '(vertical-border ((t (:foreground "Black"  ))))
 '(warning ((t (:foreground "BrightYellow"  ))))
 '(window-divider ((t (:foreground "BrightWhite"  :weight bold ))))
 '(window-divider-first-pixel ((t (:foreground "BrightWhite"  :weight bold ))))
 '(window-divider-last-pixel ((t (:foreground "Black"  :weight bold ))))
)
